### PR TITLE
Change psycopg2 dependency to psycopg2-binary

### PR DESCRIPTION
**Pull request by fuglaev**
Replace psycopg2 with psycopg2-binary

### CODE REVIEW

**Comment by fuglaev** [comment]
I can also add row to CHANGES with comment about using psycopg2-binary instead psycopg2

But I think it can be removed and can be managed with extras of sqlalchemy, right?

**Comment by rad-pat** [comment]
If you can bump the version to 0.2.1 and add a changes entry, I'll approve and release. I think it needs the to require the binary or there's no point installing the library as it won't work without.

**Comment by fuglaev** [comment]
Sorry for asking, but besides adding lines to CHANGES and VERSION, do I also need to update the version in PyPI? Or will this be a release that you will do?

**Review by rad-pat — APPROVED** [review]

**Comment by rad-pat** [comment]
Nope, I'll do the release for it 👍 Thanks

**Pull request merged**
